vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
       products:
           uri_prefix: /assets/images/products
           upload_destination: '%kernel.project_dir%/public/assets/images/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
